### ISSUE TITLE
Linked Documentation not available/offline

### ISSUE THREAD

**Issue by raspyweather** [qkmaxware/Astro#1]
hi,
sadly, the linked documentation ( [qkmaxware.github.io](https://qkmaxware.github.io/Astro/) ) seems to be no longer available.
Regards raspyweather

**Comment by qkmaxware** [comment]
So the reason the documentation isn't there is because I haven't written it yet. I had decided to first break apart this monolithic project into several smaller ones first. Once I was finished with those smaller projects I would come back here and turn this repo into a simple amalgamation nuget package for the smaller repos and then do the documentation. I was a little over-eager putting a link up. I assumed I would be done by now, but life has slowed the progress. 

So far none of the smaller projects are done but some are quite far along. 

If you want to check out some of those individual packages, you can see them all [here](https://github.com/qkmaxware?tab=repositories&q=Astro&type=&language=Cs)
The one that is furthest along in its progress is [Astro.Control](https://github.com/qkmaxware/Astro.Control) for telescope control. 
But I have other ones for astronomical catalogues, gear catalogues, units of measure, and one for common file-types used in astronomy.
